server {
    listen 80;
   # server_name facebay.local;
    root /var/www/html/public;

    index index.html index.htm index.php;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Set-Cookie "Path=/; HttpOnly; Secure";
    add_header Content-Security-Policy  "script-src *.google-analytics.com *.googleapis.com *.google.com *.jsdelivr.net *.datatables.net *.cloudflare.com 'unsafe-inline' 'unsafe-eval' blob: data: 'self';font-src *.gstatic.com blob: data: 'self';";
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/fb-error.log error;

    sendfile off;

    client_max_body_size 100m;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        fastcgi_param REMOTE_ADDR $http_x_forwarded_for;
    }

    location ~ /\.ht {
        deny all;
    }
}